
[font]
size = 9

[font.offset]
x = 0
y = 1

[window.padding]
x = 10
y = 10

[cursor]
style = "Beam"


[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.8

[colors.primary]
background =  '#181818'
foreground =  '#b9b9b9'

# Normal colors
[colors.normal]
black   = '#3b3b3b'
red     = '#ed4a46'
green   = '#70b433'
yellow  = '#dbb32d'
blue    = '#368aeb'
magenta = '#eb6eb7'
cyan    = '#3fc5b7'
white   = '#b9b9b9'

# Bright colors
[colors.bright]
black   = '#777777'
red     = '#ff5e56'
green   = '#83c746'
yellow  = '#efc541'
blue    = '#4f9cfe'
magenta = '#ff81ca'
cyan    = '#56d8c9'