
[font]
size = 11

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[window.padding]
x = 10
y = 10

[cursor]
style = "Beam"


[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.8

# Default colors
[colors.primary]
background = '#2C2C2C'
foreground = '#DCDCCC'

# Normal colors
[colors.normal]
black   = '#3F3F3F'
red     = '#705050'
green   = '#60B48A'
yellow  = '#DFAF8F'
blue    = '#9AB8D7'
magenta = '#DC8CC3'
cyan    = '#8CD0D3'
white   = '#DCDCCC'

# Bright colors
[colors.bright]
black   = '#709080'
red     = '#DCA3A3'
green   = '#72D5A3'
yellow  = '#F0DFAF'
blue    = '#94BFF3'
magenta = '#EC93D3'
cyan    = '#93E0E3'
